import 'package:flutter/material.dart';

/*
* flutter pokemon colors pokeapi
* definition of the colors by type of pokemon obtained from: https://gist.github.com/apaleslimghost/0d25ec801ca4fc43317bcff298af43c3
*
* material color generated by http://mcg.mbitson.com/#!?mcgpalette0=%23a8a77a
* */
class PokedexColors {
  static const MaterialColor normalColor =
      MaterialColor(_normalColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF5F4EF),
    100: Color(0xFFE5E5D7),
    200: Color(0xFFD4D3BD),
    300: Color(0xFFC2C1A2),
    400: Color(0xFFB5B48E),
    500: Color(_normalColor0PrimaryValue),
    600: Color(0xFFA09F72),
    700: Color(0xFF979667),
    800: Color(0xFF8D8C5D),
    900: Color(0xFF7D7C4A),
  });
  static const int _normalColor0PrimaryValue = 0xFFA8A77A;

  static const MaterialColor fireColor =
      MaterialColor(_fireColor0PrimaryValue, <int, Color>{
    50: Color(0xFFFDF0E6),
    100: Color(0xFFFAD9C1),
    200: Color(0xFFF7C098),
    300: Color(0xFFF3A76E),
    400: Color(0xFFF1944F),
    500: Color(_fireColor0PrimaryValue),
    600: Color(0xFFEC792B),
    700: Color(0xFFE96E24),
    800: Color(0xFFE7641E),
    900: Color(0xFFE25113),
  });
  static const int _fireColor0PrimaryValue = 0xFFEE8130;

  static const MaterialColor waterColor =
      MaterialColor(_waterColor0PrimaryValue, <int, Color>{
    50: Color(0xFFECF2FD),
    100: Color(0xFFD0DEFB),
    200: Color(0xFFB1C8F8),
    300: Color(0xFF92B1F5),
    400: Color(0xFF7AA1F2),
    500: Color(_waterColor0PrimaryValue),
    600: Color(0xFF5B88EE),
    700: Color(0xFF517DEC),
    800: Color(0xFF4773E9),
    900: Color(0xFF3561E5),
  });
  static const int _waterColor0PrimaryValue = 0xFF6390F0;

  static const MaterialColor electricColor =
      MaterialColor(_electricColor0PrimaryValue, <int, Color>{
    50: Color(0xFFFEF9E6),
    100: Color(0xFFFDF1C0),
    200: Color(0xFFFBE896),
    300: Color(0xFFF9DE6B),
    400: Color(0xFFF8D74C),
    500: Color(_electricColor0PrimaryValue),
    600: Color(0xFFF6CB27),
    700: Color(0xFFF5C421),
    800: Color(0xFFF3BE1B),
    900: Color(0xFFF1B310),
  });
  static const int _electricColor0PrimaryValue = 0xFFF7D02C;

  static const MaterialColor grassColor =
      MaterialColor(_grassColor0PrimaryValue, <int, Color>{
    50: Color(0xFFEFF8EA),
    100: Color(0xFFD7EEC9),
    200: Color(0xFFBDE3A6),
    300: Color(0xFFA2D882),
    400: Color(0xFF8ECF67),
    500: Color(_grassColor0PrimaryValue),
    600: Color(0xFF72C145),
    700: Color(0xFF67BA3C),
    800: Color(0xFF5DB333),
    900: Color(0xFF4AA624),
  });
  static const int _grassColor0PrimaryValue = 0xFF7AC74C;

  static const MaterialColor iceColor =
      MaterialColor(_iceColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF2FAFA),
    100: Color(0xFFE0F4F3),
    200: Color(0xFFCBECEB),
    300: Color(0xFFB6E4E2),
    400: Color(0xFFA6DFDC),
    500: Color(_iceColor0PrimaryValue),
    600: Color(0xFF8ED5D1),
    700: Color(0xFF83CFCC),
    800: Color(0xFF79CAC6),
    900: Color(0xFF68C0BC),
  });
  static const int _iceColor0PrimaryValue = 0xFF96D9D6;

  static const MaterialColor fightingColor =
      MaterialColor(_fightingColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF8E6E5),
    100: Color(0xFFEDC0BF),
    200: Color(0xFFE19794),
    300: Color(0xFFD46D69),
    400: Color(0xFFCB4D48),
    500: Color(_fightingColor0PrimaryValue),
    600: Color(0xFFBC2924),
    700: Color(0xFFB4231E),
    800: Color(0xFFAC1D18),
    900: Color(0xFF9F120F),
  });
  static const int _fightingColor0PrimaryValue = 0xFFC22E28;

  static const MaterialColor poisonColor =
      MaterialColor(_poisonColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF4E8F4),
    100: Color(0xFFE3C5E3),
    200: Color(0xFFD19FD0),
    300: Color(0xFFBF78BD),
    400: Color(0xFFB15BAF),
    500: Color(_poisonColor0PrimaryValue),
    600: Color(0xFF9B3899),
    700: Color(0xFF91308F),
    800: Color(0xFF882885),
    900: Color(0xFF771B74),
  });
  static const int _poisonColor0PrimaryValue = 0xFFA33EA1;

  static const MaterialColor groundColor =
      MaterialColor(_groundColor0PrimaryValue, <int, Color>{
    50: Color(0xFFFCF7ED),
    100: Color(0xFFF6ECD1),
    200: Color(0xFFF1DFB2),
    300: Color(0xFFEBD293),
    400: Color(0xFFE6C97C),
    500: Color(_groundColor0PrimaryValue),
    600: Color(0xFFDFB95D),
    700: Color(0xFFDAB153),
    800: Color(0xFFD6A949),
    900: Color(0xFFCF9B37),
  });
  static const int _groundColor0PrimaryValue = 0xFFE2BF65;

  static const MaterialColor flyingColor =
      MaterialColor(_flyingColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF5F2FE),
    100: Color(0xFFE5DDFB),
    200: Color(0xFFD4C7F9),
    300: Color(0xFFC3B1F7),
    400: Color(0xFFB6A0F5),
    500: Color(_flyingColor0PrimaryValue),
    600: Color(0xFFA287F1),
    700: Color(0xFF987CEF),
    800: Color(0xFF8F72ED),
    900: Color(0xFF7E60EA),
  });
  static const int _flyingColor0PrimaryValue = 0xFFA98FF3;

  static const MaterialColor psychicColor =
      MaterialColor(_psychicColor0PrimaryValue, <int, Color>{
    50: Color(0xFFFEEBF1),
    100: Color(0xFFFDCCDB),
    200: Color(0xFFFCAAC3),
    300: Color(0xFFFB88AB),
    400: Color(0xFFFA6F99),
    500: Color(_psychicColor0PrimaryValue),
    600: Color(0xFFF84E7F),
    700: Color(0xFFF74474),
    800: Color(0xFFF63B6A),
    900: Color(0xFFF52A57),
  });
  static const int _psychicColor0PrimaryValue = 0xFFF95587;

  static const MaterialColor bugColor =
      MaterialColor(_bugColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF4F7E4),
    100: Color(0xFFE4EABA),
    200: Color(0xFFD3DC8D),
    300: Color(0xFFC1CE5F),
    400: Color(0xFFB3C43C),
    500: Color(_bugColor0PrimaryValue),
    600: Color(0xFF9EB217),
    700: Color(0xFF95AA13),
    800: Color(0xFF8BA20F),
    900: Color(0xFF7B9308),
  });
  static const int _bugColor0PrimaryValue = 0xFFA6B91A;

  static const MaterialColor rockColor =
      MaterialColor(_rockColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF6F4E7),
    100: Color(0xFFE9E3C3),
    200: Color(0xFFDBD09B),
    300: Color(0xFFCCBD72),
    400: Color(0xFFC1AF54),
    500: Color(_rockColor0PrimaryValue),
    600: Color(0xFFAF9930),
    700: Color(0xFFA68F29),
    800: Color(0xFF9E8522),
    900: Color(0xFF8E7416),
  });
  static const int _rockColor0PrimaryValue = 0xFFB6A136;

  static const MaterialColor ghostColor =
      MaterialColor(_ghostColor0PrimaryValue, <int, Color>{
    50: Color(0xFFEEEBF3),
    100: Color(0xFFD5CDE0),
    200: Color(0xFFB9ABCB),
    300: Color(0xFF9D89B6),
    400: Color(0xFF8870A7),
    500: Color(_ghostColor0PrimaryValue),
    600: Color(0xFF6B4F8F),
    700: Color(0xFF604684),
    800: Color(0xFF563C7A),
    900: Color(0xFF432C69),
  });
  static const int _ghostColor0PrimaryValue = 0xFF735797;

  static const MaterialColor dragonColor =
      MaterialColor(_dragonColor0PrimaryValue, <int, Color>{
    50: Color(0xFFEEE7FF),
    100: Color(0xFFD4C2FE),
    200: Color(0xFFB79AFE),
    300: Color(0xFF9A72FD),
    400: Color(0xFF8553FC),
    500: Color(_dragonColor0PrimaryValue),
    600: Color(0xFF6730FC),
    700: Color(0xFF5C28FB),
    800: Color(0xFF5222FB),
    900: Color(0xFF4016FA),
  });
  static const int _dragonColor0PrimaryValue = 0xFF6F35FC;

  static const MaterialColor darkColor =
      MaterialColor(_darkColor0PrimaryValue, <int, Color>{
    50: Color(0xFFEEEBE9),
    100: Color(0xFFD4CDC8),
    200: Color(0xFFB8ABA3),
    300: Color(0xFF9B897E),
    400: Color(0xFF857062),
    500: Color(_darkColor0PrimaryValue),
    600: Color(0xFF684F3F),
    700: Color(0xFF5D4637),
    800: Color(0xFF533C2F),
    900: Color(0xFF412C20),
  });
  static const int _darkColor0PrimaryValue = 0xFF705746;

  static const MaterialColor steelColor =
      MaterialColor(_steelColor0PrimaryValue, <int, Color>{
    50: Color(0xFFF6F6F9),
    100: Color(0xFFE9E9F0),
    200: Color(0xFFDBDBE7),
    300: Color(0xFFCDCDDD),
    400: Color(0xFFC2C2D5),
    500: Color(_steelColor0PrimaryValue),
    600: Color(0xFFB0B0C9),
    700: Color(0xFFA7A7C2),
    800: Color(0xFF9F9FBC),
    900: Color(0xFF9090B0),
  });
  static const int _steelColor0PrimaryValue = 0xFFB7B7CE;

  static const MaterialColor fairyColor =
      MaterialColor(_fairyColor0PrimaryValue, <int, Color>{
    50: Color(0xFFFAF0F5),
    100: Color(0xFFF3DAE6),
    200: Color(0xFFEBC2D6),
    300: Color(0xFFE2AAC6),
    400: Color(0xFFDC97B9),
    500: Color(_fairyColor0PrimaryValue),
    600: Color(0xFFD17DA6),
    700: Color(0xFFCC729C),
    800: Color(0xFFC66893),
    900: Color(0xFFBC5583),
  });
  static const int _fairyColor0PrimaryValue = 0xFFD685AD;

  static MaterialColor getByName(String typeName) {
    switch (typeName) {
      case 'normal':
        return normalColor;
      case 'fire':
        return fireColor;
      case 'water':
        return waterColor;
      case 'electric':
        return electricColor;
      case 'grass':
        return grassColor;
      case 'ice':
        return iceColor;
      case 'fighting':
        return fightingColor;
      case 'poison':
        return poisonColor;
      case 'ground':
        return groundColor;
      case 'flying':
        return flyingColor;
      case 'psychic':
        return psychicColor;
      case 'bug':
        return bugColor;
      case 'rock':
        return rockColor;
      case 'ghost':
        return ghostColor;
      case 'dragon':
        return dragonColor;
      case 'dark':
        return darkColor;
      case 'steel':
        return steelColor;
      case 'fairy':
        return fairyColor;
      default:
        return normalColor;
    }
  }
}
